### ISSUE TITLE
Make a "Drag To Application" dmg for pear.ai (Mac)

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#108]
Same as title, something like this: https://apple.stackexchange.com/questions/404954/how-to-create-drag-to-applications-folder-in-dmg

This is how: https://www.youtube.com/watch?v=IadcKngK3A4

**Comment by dfl0** [comment]
What is the exact name you would like for the `.dmg` to have as well as the volume itself?

**Comment by dfl0** [comment]
![Image](https://github.com/trypear/pearai-app/assets/130588561/d672afa1-6a66-4b9a-9685-2b851f5fcbd7)

![Image](https://github.com/trypear/pearai-app/assets/130588561/f773309c-2fc3-4c8a-8720-da38b4d3e404)

I've been working on the design for the `.dmg` as well as the icon for it, and here's what they look like as of right now.

**Comment by nang-dev** [comment]
OP!!!

**Comment by nang-dev** [comment]
dfl0, the name should be PearAI-Installer

**Comment by nang-dev** [comment]
yes exaclty

**Comment by nang-dev** [comment]
@dfl0  can you send this to me? <3

**Comment by dfl0** [comment]
@nang-dev yeah, of course

**Comment by nang-dev** [comment]
Thank you @dfl0!

**Comment by nang-dev** [comment]
@dfl0 can u send me the dmg that is not read-only? I want to switch out the app to an updated one

**Comment by nang-dev** [comment]
@dfl0 yo! do you think you can help make the gb into white + pear green color stripes?

**Comment by dfl0** [comment]
![pear_installer_bg_light](https://github.com/user-attachments/assets/9245b77a-a9c7-4a51-8ea3-6dda0c0e0396)

**Comment by nang-dev** [comment]
Legendary!!
