### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by ArturGasparyan** [trypear/pearai-app#108]
Hi,

I want to use my own OpenAI API Key, which I successfully entered in PearAI. Now I want to logout or sing out off a PearAI account, which I don't need.

How can I logout?
How can I delete my PearAI account?
Thank you

**Comment by timknappe** [comment]
To sign out of your pearAI Account, you can use the integrated command "Logout of PearAI"
You can access the commands using the Keyboard shortcut ⌘ + shift + p on Mac or Ctrl + shift + p on windows, followed by typing Logout into the input bar 
![image](https://github.com/user-attachments/assets/5e38aa00-8671-466e-a657-d2e781b1c648)

**Comment by ArturGasparyan** [comment]
Thank you!

Just to clarify: I will still be able to use my OpenAI-API with the Editor?
And regarding my second question: how can I delete my PearAI account?

**Comment by timknappe** [comment]
Yes, even without a login you can use the Editor with the OpenAI api! 

If you logged in using OAuth you can use one of the following to deactivate your account by revoking the authorization:
Google: https://myaccount.google.com/connections
GitHub: https://github.com/settings/applications

If your Account is setup via your Email I kindly advise you to join the Discord to get direct support. https://discord.com/invite/AKy5FmqCkF

Please note that you dont have to deactivate your PearAI account to use the OpenAI-api with the editor.

**Comment by ArturGasparyan** [comment]
Thank you
