### ISSUE TITLE
Fix "About" version variable

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#11]
<img width="363" alt="Screenshot_2024-09-25_at_12 03 40_PM" src="https://github.com/user-attachments/assets/c8cea928-5201-4742-b1d9-85f96d469d6e">

This version is the "version" in package.json. Let's make it the "pearAIVersion" in product.json: https://github.com/trypear/pearai-app/blob/main/product.json#L4

**Comment by Fryingpannn** [comment]
Hey @sandeepsandy62, nice find! If you'd like to open a PR for I could review it!

**Comment by nang-dev** [comment]
completed
