### ISSUE TITLE
No task install-and-build as mentioned in COntributing.MD

### ISSUE THREAD

**Issue by Jaswir** [trypear/pearai-app#111]
## Describe the bug

In [pearai-app](https://github.com/trypear/pearai-app/tree/main)
/CONTRIBUTING.md

A) PearAI Submodule / Extension , step 3 refers to "In VSCode/PearAI, open the command palette (cmd/ctrl+shift+p) and select Tasks: Run Task and then select install-and-build." There is no such task is tasks.json

## How to reproduce
go to https://github.com/trypear/pearai-app/blob/main/CONTRIBUTING.md#-getting-started
Open the directory extensions/pearai-submodule in PearAI or VSCode.
In VSCode/PearAI, open the command palette (cmd/ctrl+shift+p) and select Tasks: Run Task
Look in tasks.json (no install_and_build task)

## Expected behavior

install_and_build task 

## Additional information

I have Macbook Apple M3
Use Node v20.18.0
Python 3.11.1
Yarn 1.22.22
Have Git, Rust
And Xcode and Command Line Tools installed

**Comment by samridht23** [comment]
there is install-and-build command present just make sure u have .vscode directory in pearai-submodule folder here is the install-and-build command for reference https://github.com/trypear/pearai-submodule/blob/14cbe49a2774ec61ce81e64db75bb4347b07b989/.vscode/tasks.json#L111

**Comment by Jaswir** [comment]
Thanks, I had it open in the pearai-app directory that's why the task wasn't there

**Comment by Jaswir** [comment]
![image](https://github.com/user-attachments/assets/d49d9273-b08e-4cf8-88f1-7c4d48b0b351)

**Comment by Jaswir** [comment]
Thanks, I had it open in the pearai-app directory that's why the task wasn't there.
Needed to open separate pearai/code/instructor in the pearai-submodule directory!
