### ISSUE TITLE
App can be packaged for distribution for Windows

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#117]
This is how we package the app: https://github.com/trypear/pearai-app/blob/main/CONTRIBUTING.md#packaging

and for distribution instructions: https://docs.google.com/document/d/1hZahz2UNrtZOgHZkquqNO7Jfoe0Pd0OA7Ud16ts_AKs/edit?usp=sharing (Mac so far)

we need to some extra stuff to distribute to windows users i think

**Comment by gedeondoescode** [comment]
Documented the process. Will now be moving this into review until fully confirmed the installer works.

**Comment by MaySoMusician** [comment]
@gedeondoescode 
Okay, so can we consider this issue resolved if someone manages to successfully build a package using the updated documents? I'm on Windows, so I'll test it in a VM.

**Comment by gedeondoescode** [comment]
Completed
