### ISSUE TITLE
Slash Commands Not Displaying Response since 1.5.0

### ISSUE THREAD

**Issue by charlwillia6** [trypear/pearai-app#120]
## Describe the bug

Slash commands do not display the response/output in the chat sidebar.  If you look at the PearAI output in VS Code, you can see the request is sent, and the model sends back a response, but it is never displayed in the sidebar.

## How to reproduce

Use any slash command, but I used /explain and it never shows the response.

## Expected behavior

When using slash commands, the output should be shown in the chat output bar.

## Screenshots

![image](https://github.com/user-attachments/assets/6ebd9ef3-ce2c-4410-8009-3435515d4745)

## Additional information

- Version of the extension impacted: 1.5.0

I am on Windows 11

Issue reported on Discord
https://discordapp.com/channels/1237009981803462729/1306608547966226432/1306608547966226432

**Comment by charlwillia6** [comment]
There is already a pull request and this issue has been fixed https://github.com/trypear/pearai-submodule/pull/163
@nang-dev @Fryingpannn This can be closed.

**Comment by Himanshu-Singh-Chauhan** [comment]
fixed, closing.
