### ISSUE TITLE
Change cmd+I command UI

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#129]
Current:
<img width="727" alt="Screenshot 2024-06-09 at 3 27 48 PM" src="https://github.com/trypear/pearai-app/assets/5115108/a4be0676-4d60-42d4-a4f7-f7d9ba47163b">

This should open a text box next to where your in-line cursor is  (instead of at the top of the editor

**Comment by Fryingpannn** [comment]
Duplicate issue #36
