### ISSUE TITLE
pearai_tutorial.py should open front and center upon users first opening the app (or if they click get started)

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#131]
Related to #130

**Comment by MaySoMusician** [comment]
@nang-dev @Fryingpannn 
Trying to give a shot so I'd like you to confirm my understanding.

- After installation -> Open `welcome.md`. (Already implemented)
- After an user first opens the extension (clicking the icon in Activity Bar)  -> Open `pearai_tutorial.py`. (This issue)

**Comment by MaySoMusician** [comment]
![image](https://github.com/trypear/pearai-app/assets/34566290/881e5c52-1f6a-4262-8745-b358d93fc2cb)

Currently the extension will open the tutorial file after a user clicks `Continue` button on the onboarding page.

So is it necessary to open the file in advance? We've got this comment that says not to open it until the onboarding is complete.

https://github.com/trypear/pearai-submodule/blob/fd59dae057439b11f4ac8e178307b681ff3a3c4d/gui/src/pages/onboarding/onboarding.tsx#L148-L150

```tsx
              // Don't show the tutorial above yet because there's another step to complete at /localOnboarding
              postToIde("showTutorial", undefined);
              navigate("/");
```
