### ISSUE TITLE
Remove Continue's free trial error bug

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#134]
This error should not appear. Rn it appears almost every time I open the app.

Simply need to dismiss the error for now. We could maybe reuse the free trial code for our own free trial later

<img width="555" alt="image" src="https://github.com/trypear/pearai-app/assets/59063950/92417d94-8a21-4524-9c76-0c27e8c27b72">

**Comment by Ibinola** [comment]
can i work on this ?

**Comment by Himanshu-Singh-Chauhan** [comment]
[raised pr for this](https://github.com/trypear/pearai-submodule/pull/64)
