### ISSUE TITLE
Change Help Center to PearAI info

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#147]
## Context
Modify Help Center buttons and data to reflect PearAI

## Repro
- Open Pear chat (`CMD+L`)
- See bottom right, click the `?` button. 

## Changes
- Discord -> PearAI Discord
- Github Issues -> change link to https://github.com/trypear/pearai-app/issues
- Keyboard shortcuts: add `CMD+[` with "Enlarge Pear chat" and `CMD+:` for "Close Pear chat"
- Documentation and demo video can be kept same for now until we make one ourselves

![Image](https://github.com/trypear/pearai-app/assets/59063950/13112e61-2441-4497-bb1b-0e1bcbdf6445)

**Comment by ArmaniTulip** [comment]
I'm going to take a stab at this.

**Comment by Mex777** [comment]
> I'm going to take a stab at this.

This was completed already on https://github.com/trypear/pearai-submodule/pull/65
I think Pan should close this issue
