### ISSUE TITLE
Fix setup environment file for Windows

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#148]
## Context

[Bug found by Himanshu]

Currently, windows setup is buggy due to mainly two reasons: symlinks and git submodule. We have discovered a major reason why extension doesn't show up on Windows is due to symlink not working properly. The Pear extension folder is nested within the pearai-submodule folder, thus we need a symlink from the outer extensions folder that references it directly in order for Pear to actually discover the Pear extension. If this symlink doesn't work, Pear will not pop up.

## Solution

Update setup-environment.ps1  - delete already existing symlink before creating new ones. Because if the folder is already created, the symlink may fail.

Also would be nice if some way to prevent the `setup-environment.sh` file from being ran if user is using Windows since that script is for Mac. This can prevent some unexpected errors from accidentally running the Mac script instead of the Windows.

Himanshu:
"my symlink folder somehow got converted to actual folder, don't know how, maybe i ran .sh setup script, thats why, so its better to ensure we remove the already existing symlink and then create new link."

**Comment by Himanshu-Singh-Chauhan** [comment]
I'll take this.
