### ISSUE TITLE
Add the appriopriate logos in Pear

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#152]
## Is this request related to a problem? Please describe.

Currently there's only one logo format for all places. Which is why the logo looks very big, we need to fix the sizes + change black and white to white and green logos. All needed sizes can be found in this [Figma design here](https://www.figma.com/design/ZY6jBIcZ8GF3Al2ajWZNyN/Pear-AI-Logos-With-Exports?node-id=0-1):

Simply go New Dark Green section and you can click on a size and export it as PNG.
![Image](https://github.com/trypear/pearai-app/assets/59063950/2d425239-1197-4a63-a970-ce94691916e0)

### How to know what size to put?

I previously made a PR where I changed everything to the same size. Please take a look at this PR and put the correct previous sizes with the new logo: https://github.com/trypear/pearai-app/pull/91/files

If any size is missing, let Selene (or me) know in the Discord and she can help us make the new size logo.

**Comment by mateuseap** [comment]
Hi! I'd like to work on this, if possible.

**Comment by Fryingpannn** [comment]
@mateuseap Yo! did u get a chance to work on it? Sorry just saw ur comment. Usually better if u ping me in discord.
