### ISSUE TITLE
Improve PearAI UX for choosing models

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#157]
## Context
Improve the login and choosing model flow for PearAI now that we have a PearAI server as an option.
 
## Current behaviour
Right now users choosing a model looks like this:

1. On first time app open
<img width="430" alt="Screenshot 2024-07-05 at 5 03 35 PM" src="https://github.com/trypear/pearai-app/assets/5115108/1551a8db-111d-4191-b77f-7fd164702a9f">

2. Clicking "Cloud models" goes to the chat panel, but it uses "Free trial" models (see bottom left). Users have to click the '+' on the bottom left to open up the models panel and choose a different model. (Bad cause we don't have free trial yet)
<img width="539" alt="Screenshot 2024-07-05 at 6 01 20 PM" src="https://github.com/trypear/pearai-app/assets/5115108/3744a6e8-deaa-402c-99e1-daa15c49a411">

3. At the models panel (panel where you choose models), users can select "PearAI Server", to go to the PearAI Server model panel
<img width="500" alt="Screenshot 2024-07-05 at 6 02 42 PM" src="https://github.com/trypear/pearai-app/assets/5115108/b30fe96b-4f63-4fde-b3f1-9ee0395afc0c">

4. The PearAI server model panel then looks like:
<img width="396" alt="Screenshot 2024-07-05 at 5 04 14 PM" src="https://github.com/trypear/pearai-app/assets/5115108/2b6c0cb3-3ea8-4679-aa86-340b862067ff">

## Changes needed

A couple things need to change here:

- at (4) the PearAI Server panel, make buttons look nicer: text and button size consistent.
- at (4), change last button text to "Start coding 😎"
- at (2), we don't have free trials. It should ask the user to choose a model directly (redirect to the models panel (this is the panel that appears when you click the bottom left "+")).

Secondary tasks:
- at (1), PearAI server should be an option directly (can also be another PR)
- at (4) we shouldn't even need the 'click to complete' button , after the user clicks login, it should wait the `code-oss://pearai.pearai/auth/` callback (frontend landing page opens up the app with that link) and automatically continue. This might take some elbow grease so we can do this in another PR as well

**Comment by nang-dev** [comment]
The line to look at is here: 

https://github.com/trypear/pearai-submodule/blob/be276437eefcb20517d9837234c34b149ce84c38/gui/src/pages/modelconfig.tsx#L197

**Comment by MaySoMusician** [comment]
> at (2), we don't have free trials. It should ask the user to choose a model directly (redirect to the models panel (this is the panel that appears when you click the bottom left "+")).

@Fryingpannn @nang-dev 
we have default config.json content defined at https://github.com/trypear/pearai-submodule/blob/be276437eefcb20517d9837234c34b149ce84c38/core/config/default.ts#L7-L27
should we remove them and replace with `pearai-server`'s ?

**Comment by MaySoMusician** [comment]
we also have https://github.com/trypear/pearai-submodule/blob/be276437eefcb20517d9837234c34b149ce84c38/core/config/onboarding.ts#L1
anyway, an appropriate config should be created after onboarding

**Comment by Himanshu-Singh-Chauhan** [comment]
ill take the secondary tasks a part now.

**Comment by nang-dev** [comment]
@MaySoMusician we actually should* have a free trial so it actually works out of the box. But for this beta launch lets just set it to pearai server as well as OpenAI (with no api key, theyre gonna have to input this). UX will not be perfect

**Comment by nang-dev** [comment]
S/o @Himanshu-Singh-Chauhan for doing the UI/UX flow!!!

only thing left is the default models (free trial) that need to be changed

**Comment by nang-dev** [comment]
done
