### ISSUE TITLE
Shortcut to open chat history

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#158]
## Is this request related to a problem? Please describe.

_A clear and concise description of what the problem is (e.g. "I'm always frustrated when […]")._

Right now to open chat history, one must click this button:
![Image](https://github.com/trypear/pearai-app/assets/59063950/a1488390-f0aa-421d-bfab-6122a3c78a5a)

This is not convenient. It should be easy for one to reach the history since often we want to see the previous chats.

## Describe the solution you'd like

_A clear and concise description of what you want to happen._

1. Figure out if there's currently a shortcut to reach the history tab
2. If there's no shortcut for it currently, then we need to make one (`CMD+o` or `CTRL+o`)

## Additional context

_Add any other information or screenshots about the feature request here (e.g. a gif showing how another tool does it)._

**Comment by Himanshu-Singh-Chauhan** [comment]
1. There is no shortcut to open pearai history.
2. shortcut can be added easily.

for example - 
![image](https://github.com/trypear/pearai-app/assets/26621232/6a782a1a-2a99-46f7-82d3-745f155a42f9)

need to decide what shortcut we want. `ctrl O` seems good to me, its next to `ctrl I` which is for inline opening chat box

**Comment by Himanshu-Singh-Chauhan** [comment]
added shortcut in https://github.com/trypear/pearai-submodule/pull/82  (merged)
