### ISSUE TITLE
Change Windows shortcuts from using `ALT` to `CTRL`

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#161]
## Is this request related to a problem? Please describe.

_A clear and concise description of what the problem is (e.g. "I'm always frustrated when […]")._

Currently the Windows equivalent commands such as 
- Opening chat (`CMD+L`)
- Enlarge chat (`CMD+[`)
- Close chat (`CMD+:`)
Use `ALT` in replacement of `CMD`.

However, the default behaviour of Windows users is to use `CTRL`. We should switch out `ALT`.

**Comment by Himanshu-Singh-Chauhan** [comment]
windows have ctrl alt L to close chat, i think thats better, or do we want it to be `ctrl + :`
