### ISSUE TITLE
Better handle when there are no models in config.json

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#163]
## Currently it looks like this:

<img width="537" alt="Screenshot 2024-07-09 at 10 47 39 PM" src="https://github.com/trypear/pearai-app/assets/5115108/ac905294-7fbe-4275-91c1-b29a31e0afd3">

## What is should be

It should have a button that says "Select a model"

Any chat that is attempted with no model selected should throw an error (that pops up) with "No model selected! Please select a model."

**Comment by Himanshu-Singh-Chauhan** [comment]
my issue.

**Comment by nang-dev** [comment]
some progress

**Comment by nang-dev** [comment]
https://github.com/trypear/pearai-submodule/pull/91
