### ISSUE TITLE
Fixing "Getting Started to PearAI" Walkthrough Page

### ISSUE THREAD

**Issue by cqdev-co** [trypear/pearai-app#179]
## Context

In the app (or submodule), the PearAI Getting Started page is using Continue's image page. This needs to be switched out

![image](https://github.com/user-attachments/assets/a03927a2-5692-4596-8da6-d10f572c6021)

## Solution
Change out the images/gifs to be related to PearAI

**Comment by abhinav26966** [comment]
Hi @cqdev-co ,
Could you please provide a more detailed explanation of this issue? I'm interested in working on it.

**Comment by cqdev-co** [comment]
@abhinav26966 Currently there is a GIF that use's Continue's version of a walkthrough for their submodule. This needs to be replaced with a walkthrough of our submodule instead. This requires:

- Creating own GIF of using PearAI 
- Switching out the GIF used by continue
- Any more features or QOL changes you feel are necessary

**Comment by abhinav26966** [comment]
> @abhinav26966 Currently there is a GIF that use's Continue's version of a walkthrough for their submodule. This needs to be replaced with a walkthrough of our submodule instead. This requires:
> 
> * Creating own GIF of using PearAI
> * Switching out the GIF used by continue
> * Any more features or QOL changes you feel are necessary

Alright @cqdev-co , thanks for the clarification.

**Comment by abhinav26966** [comment]
hey @cqdev-co, just needed a clarification on the gif thing
Can you tell if [this](https://github.com/trypear/pearai-submodule/blob/main/gui/public/continue.gif) is the only gif you were talking to change or there are other changes too which I have to edit.

**Comment by cqdev-co** [comment]
@abhinav26966 I can't see it play, but if it's containing anything related to Continue then it needs to be replaced

**Comment by nang-dev** [comment]
I fixed this
