### ISSUE TITLE
Resize chat in primary side bar

### ISSUE THREAD

**Issue by Himanshu-Singh-Chauhan** [trypear/pearai-app#180]
#### Describe the bug

Resizing Chat (big chat) works when the chat is in secondary side bar (auxiliary bar) which is the default location for it.
but users can change the location and drag it to primary side bar or the Panel (panel is which appear on bottom - ctrl J), there the big chat and close chat shortcuts don't work.
for now, it should at least work on primary side bar.

- Version of the extension impacted: 1st release

#### How to reproduce
drag extension to primary and try the shortcuts of big chat and close chat.

#### Solution
- register a vscode command to resize primary side bar similar to secondary.
- detect the location of extension in submodule and call the appropriate command to resize.
- if we can't detect location in extension, a workaround can be - introduce a new command in _pear-app_ for resizing, since it's in pearapp itself, it can determine the extension location and resize appropriate side bar.

**Comment by nang-dev** [comment]
Thanks himanshu!
