### ISSUE TITLE
Fix dates for PearAI.app

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#186]
Not sure why this is happening:

<img width="723" alt="Screenshot 2024-07-15 at 6 57 52 PM" src="https://github.com/user-attachments/assets/ba2d491b-427f-4314-a83a-8f6110521b90">

Lets try to fix this!!

**Comment by Pockylee** [comment]
working on it

**Comment by Pockylee** [comment]
After some research and testing, we can just simply add `touch -c {path to PearAI.app}` after stapling the notarization ticket or after codesign the PearAI.app. I will do a new version with intel app for testing soon.

**Comment by nang-dev** [comment]
Amazing, thanks pocky!
