### ISSUE TITLE
[Easy][App] Improve Shortcuts Bar UI

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#189]
## Context

We no have a Shortcuts Bar where priority shortcuts are displayed for easy user access and better UX.

## Problem

Currently things aren't precisely aligned

## Solution

- Align spacing words (spacing between for e.g. "Add" and the shortcuts should be same). 
- Align axis (for e.g. "Big" right now appears lower than the shortcuts right beside it

Current look:

![Image](https://github.com/user-attachments/assets/0576974a-6611-47a8-afa1-abf8696f86a0)

**Comment by wflore19** [comment]
✋
