### ISSUE TITLE
Transport code into chat bar automatically when selected

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#19]
Prerequisite on trypear/pearai-extension#13 

- When pressing `CMD+L`, if there is code that is already selected, it should directly copy paste that code into the chat panel as well.
- Limit to 13 lines of code shown. What overflows should be scrollable.

E.g. See the highlighted portion appear in the chat panel. 

<img width="1356" alt="image" src="https://github.com/trypear/pearai-extension/assets/59063950/3176cfba-66fe-4221-afc8-aa4b5e900c5e">

**Comment by ItWasEnder** [comment]
I shall take it
