### ISSUE TITLE
[Easier][App] Prevent the cancel prompt button from scrolling with chat

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#190]
## Problem

Currently when prompting the chat, as Pear generates a response, the "Cancel" button goes down with the generated response, making it difficult for the user to click on it to cancel, especially when requires user to scroll down.

![Image](https://github.com/user-attachments/assets/e7c87003-3cde-4ca4-9fb8-a3ed3fa10f51)

## Solution

- Make button Sticky: While generating, the "Cancel" button should still show, but hover over the rest of the chat in the same bottom position, such that even when the generated text keeps going down, we can still see the cancel button, until the text is fully generated.

**Comment by Himanshu-Singh-Chauhan** [comment]
i am working on this.
