### ISSUE TITLE
[Easier][App] Improve onboarding experience

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#192]
Key ideas
- Missing shortcuts in the welcome page
  - Key shortcuts show up: all the ones in Shortcuts Row
  - Can also refer to Help Center (bottom right of chat panel)
- Tutorial page doesn't show up
  - On the welcome page, should at least refer/redirect to the tutorial. So that people can know
- The welcome page should be accessible from the home page of PearAI (when you don't have any folder open)
![Image](https://github.com/user-attachments/assets/73680807-30d2-4822-b7ae-579f60d959c2)

**Comment by Fryingpannn** [comment]
ECLIPSE WORKING ON THIS

**Comment by jspEclipse** [comment]
^

**Comment by jspEclipse** [comment]
all I have left is to add welcome page in home page
