### ISSUE TITLE
[Medium][App+Server] "Premature close" error

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#194]
*** **Requires access to server repository** ****

## Describe the bug

Reported by @Himanshu-Singh-Chauhan [here](https://discord.com/channels/1237009981803462729/1261895264382484520/1262719423387668501).

Sometimes the response of a prompt gets interrupted with the following message "Premature close" and removes whatever answer that was received as it wasn't complete.
![Image](https://github.com/user-attachments/assets/fd54640b-a0a1-47f9-8c84-3627900fd254)

## How to reproduce

_Please detail steps to reproduce the behavior. Add code if necessary._

## Expected behavior

_Clear and concise description of what you expected to happen._

- We must investigate the source of the "Premature close". Is it because of a certain request timeline deadline being too short? I think some limit has been set on the PearAI app side that is causing it to prematurely cancel the streamed response. Could also be we're missing something when making the API request to OpenAI. (currently we use 'chat.completion.create', see [server file](https://github.com/trypear/pearai-server/blob/main/api/app/services/llm/openai_service.py#L26))
- Expected behavior should be that the entire message is returned appropriately even if it's long. And in any case, it should not erase messages that was already generated.

**Comment by nang-dev** [comment]
This is only for server

Fixed serverside
