### ISSUE TITLE
[Medium][LandingPage+Server] Indicate to user how many requests they have left

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#197]
** Requires server access **

## Is this request related to a problem? Please describe.

Reported by jyo in [Discord](https://discord.com/channels/1237009981803462729/1261895264382484520/1262397176517230632).

We should indicate to the user how many requests they have left out of the 1000 monthly limit.

In the future, we should also allow user to add more if they reach their limit.

## Describe the solution you'd like

**Frontend**
On the landing page's settings' page, in the Usage section, simply indicate "X/1000 requests used".

**Backend**
Make an endpoint that checks our Redis and retrieves how many requests the user has used so far and returns to the front end.

**Comment by wflore19** [comment]
I can work on this 🙋‍♂️

**Comment by Fryingpannn** [comment]
Still need help for backend side!

**Comment by wflore19** [comment]
Frontend ready. Need help with backend @Fryingpannn 

> Backend
> Make an endpoint that checks our Redis and retrieves how many requests the user has used so far and returns to the front end.
