### ISSUE TITLE
Shortcut to change chat size dynamically

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#20]
`CMD+[` should resize the chat panel to this size AND close the left side folders. 
- This is used for when there's a lot of AI text that needs scrutinizing. 
- Pressing the shortcut again should bring it back to the regular size and open the left side folders back up.
- Pressing this shortcut when the chat panel is not open should do nothing. It only acts as a re-sizer for when the chat panel is already open.
<img width="1725" alt="image" src="https://github.com/trypear/pearai-extension/assets/59063950/96292212-1b2a-489d-9756-0626bee6f7a5">

Regular size
<img width="1728" alt="image" src="https://github.com/trypear/pearai-extension/assets/59063950/a327c8f3-c357-43e9-83cc-72016518c7c9">

**Comment by Trifall** [comment]
I'll take a stab at this if no one has yet. Can you reupload the images for the approximate size for the window? They seem to have broken.
