### ISSUE TITLE
[Medium][App] Fix Copilot in PearAI

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#200]
## Is this request related to a problem? Please describe.

Raised by PockyLee: [Discord context](https://discord.com/channels/1237009981803462729/1263185355897835601/1263185363548111019)

- Copilot extension does not work within PearAI. You can see that the autocomplete code suggestions do not appear.
- This is due to the "proposed-api" being disabled. I think because copilot is synced with the latest version of VSCode, so different versions of the fork, including Code OSS (ours), will by default not sync the newest API for security reasons or prevent breaking changes.

## Describe the solution you'd like

The solution to this is for us to enable proposed-apis within PearAI.

I managed to fix this by enabling it within the runtime arguments as follows:
- `"enable-proposed-api": ["github.copilot"]`
![Image](https://github.com/user-attachments/assets/13756e5d-95df-4ce6-b7e4-c74ee908c879)

However this is a manual change that each user must perform. We need this to be programmatically done for every packaged version of PearAI. Thus, we must investigate how to do so, so that everyone who uses PearAI can also have the Copilot autocomplete feature, which we will soon implement ourselves.

## NEW INFO

See discord chat: https://discord.com/channels/1237009981803462729/1261701794510274662/1263522145535787010

Need to update product.json for many extensions.

**Comment by nang-dev** [comment]
Fixed ^
