### ISSUE TITLE
[Medium][App] Fix Remote SSH

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#201]
## Context

The extension in question that's not working: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

Problem:
- Add a new ssh host from the command pallette --> Get the following error
![Image](https://github.com/user-attachments/assets/eb283063-bb1a-4b61-b907-7aa5169d1afa)

## Solution

**Possible** the solution to this is same as #200 (Context: https://discord.com/channels/1237009981803462729/1261701794510274662/1263522145535787010)

**Comment by nang-dev** [comment]
Fixed ^
