### ISSUE TITLE
[Hard][App] Pear chat is slow on initial startup

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#202]
## Describe the bug

See the entire context in this Discord thread: https://discord.com/channels/1237009981803462729/1263317982566809671

Basically, on first app open, the Pear chat, loading the available models, is very slow. (loading config.json). Possibly due to circular dependencies.

@Himanshu-Singh-Chauhan is currently investigating.

**Comment by nang-dev** [comment]
Fixed

**Comment by Himanshu-Singh-Chauhan** [comment]
@nang-dev is there any pr or fix you did or was it through nuke merge, I want to see what the problem was
