### ISSUE TITLE
[Easy] Fix Login Shortcut redirect url

### ISSUE THREAD

**Issue by Ellahinator** [trypear/pearai-app#206]
## Describe the bug

when using `cmd shift p` to login, it takes us to `https://trypear.ai/signin?redirect=pearai://pearai.pearai/auth%3FwindowId=1`, 
![image](https://github.com/user-attachments/assets/35ff43ac-38b8-4265-8dfc-256877775f32)

![image](https://github.com/user-attachments/assets/2bd38338-6e79-4011-876d-4ab76f2ac0e0)

but our frontend doesnt handle this correctly. our frontend is looking for a `callback` not a `redirect`
and im not sure if the `%3FwindowId=1` is needed at the end of the url (if we just change `redirecct` to `callback`, signin attempt fails with this in the url so it should be removed if not needed or handled correctly in frontend)
## Expected behavior

instead of `redirect` it should be `callback` so it is handled correctly.

## Additional information

Need to handle `%3FwindowId=1` on the frontend.

**Comment by Ellahinator** [comment]
I will work on this

**Comment by nang-dev** [comment]
oh interesting. insane find and fix. thank you
