### ISSUE TITLE
pearai.pearai not found bug during developing

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#210]
## Describe the bug

When running the extension via vscode debugger, i get: 

<img width="532" alt="Screenshot 2024-07-25 at 2 15 42 AM" src="https://github.com/user-attachments/assets/aaf45b35-57bf-4886-b507-929715788584">

## How to reproduce

running the extenison via vscode debugger 

## Expected behavior

_Clear and concise description of what you expected to happen._

## Screenshots

_If applicable, add screenshots to help explain your problem._

## Additional information

- Version of the extension impacted: _vX.X.X_

_🧙‍ Add any other context about the problem here._

**Comment by nang-dev** [comment]
Himanshu had this before and runs:

`#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# Change to the VS Code extension directory and build
cd extensions/vscode
npm run tsc
node scripts/prepackage.js
npm run esbuild
cd -

# Change to the GUI directory and build
cd gui
npm run build
cd -

# Inform the user that the build is complete
echo "Build process complete."`

It worked for me before but now its not working anymore wtf

**Comment by nang-dev** [comment]
Quitting and reopening PearAI resolves this for me

**Comment by Himanshu-Singh-Chauhan** [comment]
yeah, I also get this sometimes, when I run the extension through vscode debugger, to fix it you don't need to quit it, just reload the extension window after 2 seconds, it will work.

my best guess is that when we run extension, vscode opens the extension in new window but the compilation process running is not completed yet (notice it open 2-3 terminals to watch and compile) and so the extension.js in out folder is either not generated yet or its locked, that is its being used by that terminal, so other process cant find or use it.

**Comment by nang-dev** [comment]
Nvm i still get it sometimes.

You have to run the debugger twice

**Comment by BenVN123** [comment]
> if you already had ran extension before and closed it, make sure to close the terminals created by debugger inside vscode

+1 on this, deleting all debugger terminals before running the extension fixes the issue

**Comment by nang-dev** [comment]
Fixed
