### ISSUE TITLE
[Medium] Auto add to config.json upon login / remove "Start coding"

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#213]
## Context

Right now, it looks like this:

<img width="426" alt="Screenshot 2024-07-29 at 8 21 37 PM" src="https://github.com/user-attachments/assets/9f8de80b-4d78-4b92-86ae-3981e2111218">

The button is needed to add the new settings to config.json. But upon a successful login, this should happen automatically!

The 3. Click To Continue should not be needed

**Comment by cqdev-co** [comment]
I'll give it a shot

**Comment by nang-dev** [comment]
S/o himanshu
