### ISSUE TITLE
[Easy][App] Shortcuts Bar Improvements

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#214]
# Current Look

![Image](https://github.com/user-attachments/assets/cab5873f-9504-47b4-8c13-9c51cdf3c31e)

# Expected Look

- `Add CMD SHIFT L` should be last
- Add `History CMD o`
- Change "Last" to "Prev"
- Complete order should be: Big, Last, History, Close, Add

**Comment by abhinav26966** [comment]
Hi @Fryingpannn ,
Could you please provide a more detailed explanation of this issue? I'm interested in working on it.

**Comment by jspEclipse** [comment]
I got it mb

**Comment by abhinav26966** [comment]
> @abhinav26966 I think someone is already tackling this! Btw do join the discord and ping me directly, easier for me to see.

Alright, got it.

**Comment by jspEclipse** [comment]
![Image](https://github.com/user-attachments/assets/c1b72361-0485-47dc-958e-45343b1db9b5)
This is before



![Image](https://github.com/user-attachments/assets/55c83ecd-f87a-47e8-b498-dabed8a16215)
This is after

made all requested changes. and should be completely finished
