### ISSUE TITLE
Changing the URL pearai-submodule ReadMe repo

### ISSUE THREAD

**Issue by oracle-code** [trypear/pearai-app#219]
## Context
The URL behind the PearAI Contributing for pearai-submodule is wrong. It is bringing to a 404 page.

Please see screeshots below:

![image](https://github.com/user-attachments/assets/cac42bf9-1cc9-4e2e-8770-8e21ec88cc1e)
![image](https://github.com/user-attachments/assets/288f97b2-143d-4b3f-96ad-ee0a5f4a21aa)

Problematic url : https://github.com/pearai/pearai-app
## Solution
Changing the url for : https://github.com/trypear/pearai-app/blob/main/CONTRIBUTING.md

**Comment by nang-dev** [comment]
nice! :D
