### ISSUE TITLE
[HIGH PRIORITY] Make chat open by default on the right side

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#22]
When Pear opens, the Pear Chat should be open by default on the right side of the editor.

The right side panel in the codebase is called the Auxiliary Bar (`auxiliaryBarPart.ts`). Currently this panel by default is empty, and the user can drag in extensions into this view. However, we want to auxiliary bar part to only host the pearai-submodule extension (pear chat). 

The user can open and close the panel, but only the pear chat should be visible from within this panel.

<img width="1012" alt="image" src="https://github.com/trypear/pearai-app/assets/59063950/cf7b0bed-4be1-4d27-8bc4-d70902e71392">

**Comment by shhvva** [comment]
I am working on it!!

**Comment by Fryingpannn** [comment]
@gedeondoescode  and I have tried this issue before with no success. Would be great if anyone can tackle this for the time being.

Some notes about this I took when I was trying it can be found in this [discord message](https://discord.com/channels/1237009981803462729/1247677218348466238/1247700653225279630).

**Comment by Pockylee** [comment]
I'll give it a shot!

**Comment by Fryingpannn** [comment]
More context of discussion around this feature: [Discord message](https://discord.com/channels/1237009981803462729/1243588104363839521/1253097369373900892)

**Comment by Himanshu-Singh-Chauhan** [comment]
.

**Comment by gedeondoescode** [comment]
Has been completed by @Himanshu-Singh-Chauhan. Thanks!
