### ISSUE TITLE
[Easier] Replace continue gifs from welcome

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#226]
As descriptions states! :D 

![Screenshot 2024-08-04 at 3 25 04 PM](https://github.com/user-attachments/assets/312dc493-6bb4-48e4-b141-899ab084525c)

We would need the equivalent screenrecording gifs, but using the current version of PearAI

**Comment by Tharunn25** [comment]
hey nang-dev can you please guide me where is the text located in the webpage so that i can change, Thank you

**Comment by nang-dev** [comment]
@Tharunn25 This is not in the webpage but rather pearai-submodule

**Comment by nang-dev** [comment]
@Tharunn25 Updated in the desc! pls lmk if you can take this up :D

**Comment by Pockylee** [comment]
picking this!
