### ISSUE TITLE
Fix "Quick Fix" -> "Ask PearAI"

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#231]
## Context

when there is an error in the code, you can hover over the error to get:

![Screenshot 2024-08-05 at 12 51 49 AM](https://github.com/user-attachments/assets/3df28ef0-2e00-40f9-bcc2-abc64880648d)

![Screenshot 2024-08-05 at 12 51 55 AM](https://github.com/user-attachments/assets/ce1d70d6-bb96-4fe4-bd8a-adc8c3960ff6)

![Screenshot 2024-08-05 at 12 52 00 AM](https://github.com/user-attachments/assets/1ec3e81e-585a-4fb6-938a-3081ab1c4751)

The issue is that the text should not be in the above text box, but rather fill the user's current text box.

**Comment by BenVN123** [comment]
i'll claim this one 🖐️

**Comment by nang-dev** [comment]
This is resolved in the latest change incomming!
