### ISSUE TITLE
[Easy][LandingPage] FAQ section on main page

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#238]
## Is this request related to a problem? Please describe.

Many people ask the same questions, need a FAQ for fast redirect and for average person to quickly understand.

## Describe the solution you'd like

- Add a FAQ page + Add it to navbar and footer
- The FAQ page should display each question and answer directly. No need for accordion.

The questions for now would be:
0. Why is PearAI called PearAI?
> Pear programming... Pair programming... PearAI Pair programming!
2. What separates PearAI from Github Copilot?> PearAI will provide better quality responses, and also has a better UX. These are the 2 key factors in accelerating your coding workflow. For both of these factors, you can try the free trial, and you'll be able to see the proof for yourself.
3. Why should I switch to PearAI? 
> PearAI is a fork of VSCode, and possess all of its functionalities, but also adds more to it by integrating AI functionalities to speed up your coding workflow. Current users have expressed that their coding workflow accelerated by at least 3-4x.
3. Why can't I just use ChatGPT/Claude/etc. directly instead?
> You can, and we used to as well. However, the convenience of the chat being integrated into the editor, along with easy access features within the chats such as including other files, applying changes directly, removing the need to copy paste code, prompting with code context, adding other websites or docs links in chat directly, all of this and more, means that you have a much more seamless coding experience, resulting in significant overall faster development. Try it yourself!
4. Is PearAI an extension or an app? PearAI is an app and requires you to download it.
> PearAI is an app and requires you to download (hyperlink download) it. Being a VSCode extension severely limits the modifications we can do. In order to provide the best UX possible, we need full control of code changes within the app.
5. How can I contribute to PearAI?
> See the contributors' section. (hyperlink to the new Contributing page)

**Comment by olesuv** [comment]
@Fryingpannn i guess issue already done
