### ISSUE TITLE
[Medium][LandingPage] Contributors Page

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#240]
## Is this request related to a problem? Please describe.

We need a dedicated page on the website for all information regarding contributing to PearAI so that newcomers aren't overwhelmed by the massive amount of information.

It is important to pick the most important information to show, and disregard or deprioritize those that aren't. We need to minimize the information, and only keep what's needed

## Describe the solution you'd like

I will write down text in this [document](https://docs.google.com/document/d/1oLRyjHnkUt2KMHJ8T80XnOxhcLUmvMzuwNugsGgo_vw/edit) (WIP) that will contain texts and major sections that need to be put on the page. If you'd like to be added to it, ping me on Discord and I'll give you edit access if necessary.

The structure of this page should look similar to this [one](https://docs.continue.dev/intro), where on the left side there is a table of contents and on the right side is the information displayed.

------------

FAQ 

- What techstack does PearAI use?
-

**Comment by cqdev-co** [comment]
Didn't we have someone working on this? @Fryingpannn

**Comment by Fryingpannn** [comment]
@cqdev-co Yes a few, but not satisfactory rn

**Comment by robertalv** [comment]
Would love to help out here

**Comment by ImanKahlila** [comment]
> @cqdev-co Yes a few, but not satisfactory rn. I will do some designs before assigning anyone.

I would like to be assigned to this if possible. I checked out the Figma designs.
