### ISSUE TITLE
[Easy][App] Make shorcuts and documentation more obvious

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#242]
## Is this request related to a problem? Please describe.

New users said it was unclear how to find documentation to see shortcuts, as well as how to open chat and use features.

## Describe the solution you'd like

- Put `New Chat / Add Selected (CMD+L)` on the top right of the code editor so it's always shown. (CTRL+L for windows). This should also be a button so user can click to activate CMD+L.
![Image](https://github.com/user-attachments/assets/8ea5302f-be8a-4ff5-ab7c-b87dcfee791a)
- Add `Docs` button to the editor. This will link to the new Documentation page on the landing page (WIP).
![Image](https://github.com/user-attachments/assets/c6221610-dbb2-43f4-bd1f-29e44b1895fb)
- Change "Add Selected" to "Append Selected"
![Image](https://github.com/user-attachments/assets/4b043faa-ceeb-4af9-bb0c-6849560e1b27)

**Comment by jspEclipse** [comment]
Mine
