### ISSUE TITLE
[Easy][App] Error on auth should have button for login

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#244]
## Context

Currently when you type in the chat panel chat, if not logged in it will show error message, but also a button that says log in that directs you to log in from the website. This is good UX

## Solution

We need the same for the `CMD+i` feature. The inline prompting currently doesn't have log in button when auth error.

Can refer to https://github.com/trypear/pearai-submodule/pull/109

**Comment by wflore19** [comment]
🙋‍♂️
