### ISSUE TITLE
[Medium][App] Fix lag on first app install + CMD+I issues

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#246]
## Is this request related to a problem? Please describe.

Was user testing with other people who are trying the app, on first install
- One person using windows said chat did not open on right side by default. We need to verify this. The chat should be open by default.
- `cmd+i` is hella slow for first couple uses.... Need fix urgently.
- `cmd+i` when prompted, has no loading animation so user doesn't know if working or not. Need loading animation (e.g. don't close to quickpick on top and display loading state in it)

Most importantly, we need to find a way to reproduce the "fresh app install first time" state. Currently if you just reinstall, there is cache and such that makes it not the same.

**Comment by nang-dev** [comment]
We might just need a loading in the beginning

**Comment by nang-dev** [comment]
Its time to lock in!

**Comment by nang-dev** [comment]
i think this might be fixed soon

**Comment by nang-dev** [comment]
Fixed
