### ISSUE TITLE
[Hard][App+Server] Tab Autocomplete Feature

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#249]
## Is this request related to a problem? Please describe.

We need autocomplete feature (suggestions shown, user can press tab to autocomplete). @jespiron Previously made changes but I don't think it is working properly.

We also have to do some design regarding how this will work for the request counts. I think we may need a different AI server for autocompletes (Codestral).

![Image](https://github.com/user-attachments/assets/eb58b827-51b6-4588-a2c1-e9d5553ef731)

In `config.json` (open as below in screenshot), you can see the `tabAutocompleteModel` field which indicates which model is being used for the autocomplete. This is not working properly and one will get errors shown (if it's ollama (default), you may have been seeing ollama errors), we need to change this default model.

![Image](https://github.com/user-attachments/assets/078cc579-6404-4a75-b653-f4594b59352d)

**Comment by SudhaRatan** [comment]
Hey, how can I use local ollama model for autoComplete? Thanks
