### ISSUE TITLE
Make "Continue Generation" More visible

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#250]
![Screenshot 2024-08-06 at 7 33 01 PM](https://github.com/user-attachments/assets/7f46e8b4-05e3-4eb8-b79f-86069ef75cf7)

Right now, it only comes up if you hover over. It should be its own text!

**Comment by vedantgrover** [comment]
I tried replicating this by myself but I can't seem to even get the Continue Generation button to show up. Could you show me the steps I need to take to get the button to appear?

Currently this is what I see:
<img width="476" alt="image" src="https://github.com/user-attachments/assets/0c549481-86fd-4fe3-ac0b-9952b4671a79">

**Comment by nang-dev** [comment]
To replicate:

use GPT-4o (tinyllama is also okay probably)

highlight a super long file, CMD+L to add it to the chat, and ask "Write me this with added print for each line"

itll generate something super long and stop generating at some point, and you can do the continue generation

**Comment by vedantgrover** [comment]
@nang-dev Looks like akash3444's PR fixes this issue so I'll assign it to them and let you review that.
