### ISSUE TITLE
[Medium] Cmd+L should not create a new chat

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#251]
![Image](https://github.com/user-attachments/assets/645909f5-1e82-43dc-8a4c-7901b805a73e)

CMD+L creates a new chat, even when one is in being used. We want to have it NOT create a new chat

**Comment by Fryingpannn** [comment]
yo wait a min, I think it's good that cmd+L creates new chat. Dm'ing u

**Comment by Fryingpannn** [comment]
could change cmd+shift+L to new chat, and cmd+L to append to chat

**Comment by nang-dev** [comment]
https://github.com/continuedev/continue/pull/1750/files#diff-1e86c0e2337277511427f1ccba9bee2293566ebfddc73c706c156135d519aa5b

**Comment by vedantgrover** [comment]
I can do that really quick and open up a PR for you to see it

**Comment by nang-dev** [comment]
@vedantgrover so you pushed the pearai-app changes. if you look at your PR, the changes are not there. what you wanna do is 

cd into extensions/pearai-submodule, and do the whole git push flow. the PR will appear in https://github.com/trypear/pearai-submodule/tree/main/.github

thanks!

**Comment by vedantgrover** [comment]
I've been trying to get it to push but it keeps saying I don't have access to push. Here's the error

remote: Permission to trypear/pearai-extension.git denied to vedantgrover.
fatal: unable to access 'https://github.com/trypear/pearai-extension.git/': The requested URL returned error: 403

Currently I am on my own forked repository and I push to the pear-ai submodule section of that repository

<img width="362" alt="image" src="https://github.com/user-attachments/assets/1b2f1add-912e-4791-b1d7-6f14815df663">

**Comment by nang-dev** [comment]
Ugh, sorry - we had changed pearai-extension to pearai-submodule and did not reflect this in .gitmodules.

when you re in pearai-submodule can you try a 

git remote add fork {URL TO YOUR FORK OF PEARAI SUBMODULE}

and then 

git push fork

lmk if this works?

**Comment by vedantgrover** [comment]
I've been troubleshooting this all day today. I believe I am close to getting it to work. I'll try getting a PR done by tonight

**Comment by vedantgrover** [comment]
@nang-dev There we go. Finally got it to work and the PR with the new code is in the submodule repo
