### ISSUE TITLE
[Medium][App] Fix Python intellisense / Pylance

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#255]
## Describe the bug

Python intellisense not working properly when opening python codebases in PearAI. E.g., you cannot click into a function. In the same codebase, it works in VSCode. So definitely some configuration stuff that is not setup properly.

## How to reproduce

- Have Python extension installed
- Open any python project
- Try to click into functions (should bring you to that function's definition but it doesn't)

**Comment by nang-dev** [comment]
https://www.reddit.com/r/vscode/comments/15zt8ca/pylance_is_not_working_on_my_vscode/

https://github.com/VSCodium/vscodium/discussions/1641

https://github.com/getcursor/cursor/issues/973

Ok I tested pylance v2023.1.10  and it works
Im not sure what the long term solution is, seems like ppl come up with manual hacks to get latest pylance to work
We could try to automate it but Microsoft seems to comes out with patches to counter these hacks

I think either 

1. we port it to be built-in pearai by default
2. find out how to make pylance version default to that working one when a user tries to go install
3. change UI to indicate to user they have to install a specific version

**Comment by nang-dev** [comment]
I fixed this but we need to block extensions like pylance from being downloaded from marketplace
