### ISSUE TITLE
[Easy][App] Perfect UI margins

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#256]
## Is this request related to a problem? Please describe.

We need to look professional, and in order to do so, we must be wary of details.

This is the current look of the shortcuts bar, which, although is very useful, looks slightly janky. We had customer report that it triggers their "OCD".

If you look closely, the margins between the top and bottom of the shortcuts bar, and left and right, are not equalized. These need to be consistent

![Image](https://github.com/user-attachments/assets/6e1b9b92-5c98-4d5e-b48f-ce1bbdd8507d)

Bonus
- Add little ">" arrow in the shortcuts bar on the right or left side to appear to indicate scrollable. (only should appear if not already scrolled to the max)

**Comment by SHADOW-LIGHTS** [comment]
working on this

**Comment by jspEclipse** [comment]
I'm working on this now XD

**Comment by SHADOW-LIGHTS** [comment]
I have done the changes would have created a pr yesterday but due to recent update to submodule I couldn't create a pr. if you could do the chat section it would be great.

**Comment by SHADOW-LIGHTS** [comment]
> Can you elaborate on what you mean by chat section?

<img width="242" alt="image" src="https://github.com/user-attachments/assets/6086bcac-6d1e-4913-9075-5e8b9504acf7">

I meant this.

You can submit pr if you have made any changes.
As i have spent time on it, i will create a pr too after completing it.
