### ISSUE TITLE
Figure out design for Codebase Context functionality (RAG)

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#26]
## Context
We need to figure out design for Codebase Context functionality (RAG).

Open to suggestions!

**Comment by rufimelo99** [comment]
Prior to this, one thing that you folks will probably need is to define some sort of Query Handlers Interface.
The reason for this is that you might decide to use BM25, an encoder or mix any of the possibilities that you will have.

Keep in mind that down the line, you might end up training a small encoder for this context.

I would say to think about an interface that would allow you to mix methods freely 🙂

**Comment by nang-dev** [comment]
Got this with continue
