### ISSUE TITLE
[Medium][App+Server] Model switch feature on app UI

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#271]
## Is this request related to a problem? Please describe.

Currently, we only show PearAI Server as our model. We want two other choices built-in for GPT4o and Claude 3.5 Sonnet. They should always appear below in the dropdown as available options. We already have Claude and GPT integrated in our server.
![Image](https://github.com/user-attachments/assets/1810bbc8-cd43-4b13-ac6f-3431d9572fe9)

## Describe the solution you'd like

- Dropdown should show GPT4o and Claude 3.5 Sonnet as options always. PearAi server should be "PearAI Server (Recommended)"
- Prepend the shortcut text with "Press" and add a +, so "Press cmd+' to toggle"

**Comment by Ellahinator** [comment]
ill work on the server part of this issue
