### ISSUE TITLE
[Easy][LandingPage] Add demo to about page

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#272]
## Is this request related to a problem? Please describe.

Add my twitter demo to the landing page's about page so people know how it works!

https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FCodeFryingPan%2Fstatus%2F1825456010862956844&widget=Tweet

![Image](https://github.com/user-attachments/assets/0a8a44c8-c048-4c9b-8a1b-203965ed6a60)

**Comment by SHADOW-LIGHTS** [comment]
Working on this

**Comment by SHADOW-LIGHTS** [comment]
https://github.com/trypear/pear-landing-page/pull/227#issue-2485323974
this pr solves this issue
