### ISSUE TITLE
[Easy][App] Make left activity bar by default folded onto top

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#273]
## Context

We want this left activity bar to be folded into the top of the left panel by default. Since we have right side chat panel now, we want more horizontal space by default.

![Image](https://github.com/user-attachments/assets/b7e2c31b-cb10-464d-bf37-14aa11c7e701)

![Image](https://github.com/user-attachments/assets/ca79a844-15e0-4c2e-83a4-ad9bcf62994c)

## Solution

You can try this on your editor by pressing `CMD+SHIFT+P` and clicking `Move Activity Bar to the top`. We want this to be default

**Comment by Himanshu-Singh-Chauhan** [comment]
raised a pr in sub
