### ISSUE TITLE
[Easy][App] Fix shortcuts for big chat

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#277]
Currently to enlarge chat the shortcut is `CMD+[`.

However, we had 2 complaints regarding people already using it for indentation.

Solution:

1. Change big chat to `CMD+\` (`CTRL+\` on Windows) instead
2. Change current `CMD+\` (tab splitter) functionality to (`CMD+OPTIONS+\` for Mac, and `CMD+ALT+\`)
3. Modify shortcuts bar, welcome page, help page (the previous 3 are in app), and documentation (landing page) (go to new [docs repo](https://github.com/trypear/pearai-documentation)) to reflect new changes

**Comment by MaxFSP** [comment]
https://github.com/trypear/pearai-submodule/pull/171
here is the pr from the submodule, there is still some changes to be done in the app side.
will be committing those changes shortly

**Comment by MaxFSP** [comment]
Changed big chat to CMD+\ (CTRL+\ on Windows) instead of the old shortcut CMD+] ( CTRL + ] on Windows) 
Changed current CMD+\ (tab splitter) functionality to (CMD+OPTIONS+\ for Mac, and CMD+ALT+\)
Modified shortcuts bar to display correct shortcut

**Comment by MaxFSP** [comment]
https://github.com/trypear/pearai-documentation/pull/2
Pr updating the shortcut on the documentation
