### ISSUE TITLE
"Open Tutorial" Button should check if user is logged in. 

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#281]
![Screenshot 2024-08-27 at 3 08 26 PM](https://github.com/user-attachments/assets/3afc338f-3d52-4a6c-b21a-d03a1410b0db)

This button opens: 

![Screenshot 2024-08-27 at 3 10 10 PM](https://github.com/user-attachments/assets/3eb69411-9753-4576-841a-29c8a5238a2c)

If the user is already logged in, it should go straight to the chat!

**Comment by Alvarixxs** [comment]
i'll take this

**Comment by nang-dev** [comment]
thanks alv!
