### ISSUE TITLE
Default pearai server models should be in model list no matter what

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#282]
## Context

So, after processing config.json, we add pearai server models there if they arent in config.json

This allows it to work for old versions of pearai

bonus points if on activate.ts , we poll the server for the mandatory models. that could be a part 2 tho. HIGH PRIO!

**Comment by Hi-Van** [comment]
I'll take a look at this

**Comment by nang-dev** [comment]
@Hi-Van AMAXING, we need this really bad

**Comment by nang-dev** [comment]
by 8pm est before code freeze

**Comment by Hi-Van** [comment]
if its 8pm tonight, no promise. I'm FTE so I don't have much time during the weekdays

**Comment by Hi-Van** [comment]
Issue is fixed in [Pr #181](https://github.com/trypear/pearai-submodule/pull/181) in submodule repository
