### ISSUE TITLE
Python Intellisence not working

### ISSUE THREAD

**Issue by Mustafa-raja** [trypear/pearai-app#293]
## Python Intellisence not working

Modules do not get recognised by pearai, i have all necessary extensions enables (exported from vscode when i installed pearai). My env is correctly setup. I also checked it on my VsCode and it is working fine on there. 

Modules are not being recognised and i work with typeScript also PearAI works with that flawlessly.

**Comment by Mustafa-raja** [comment]
Fixed the issue, it was not only **`pylance`** as mentioned here [https://github.com/trypear/pearai-app/issues/263](url) but also **`IntelliCode`** extension, it forces IDE to rely on **`pylance`**, now i also code in java so i needed **`IntelliCode`** so i deleted **`pylance`** then went into the settings of **`IntelliCode`** and turned off its support for python. Doing this fixed my problem.

**Comment by Mustafa-raja** [comment]
Fixed the issue, it was not only **`pylance`** as mentioned here [https://github.com/trypear/pearai-app/issues/263](https://github.com/trypear/pearai-app/issues/url) but also **`IntelliCode`** extension, it forces IDE to rely on **`pylance`** even when **`pylance`** is not downloaded in extensions, now i also code in java so i needed IntelliCode so i deleted **`pylance`** then went into the settings of **`IntelliCode`** and turned off its support for python. Doing this fixed my problem.

**Comment by nang-dev** [comment]
oh shoot. Thanks sm for finding the solution!

**Comment by Mustafa-raja** [comment]
@nang-dev 
Always a pleasure! By the way, I'm really loving Pear-Ai, and your content is amazing!
