### ISSUE TITLE
Wrongful detection of plan used - limited requests to 40 but displays 0.1% used

### ISSUE THREAD

**Issue by Fortranibal** [trypear/pearai-app#296]
## Describe the bug

It seems to not understand what my real request limit is as it is not logging in correctly. From 04/08-04/09 my quota was 1000 requests, but now it is probably not detecting my login. 

```bash
HTTP 403 Forbidden from https://stingray-app-gb2an.ondigitalocean.app/pearai-server-api2/server_chat {"error":"Unfortunately, you've run out of free trial requests. You have reached the maximum free quota of 40 requests. Subscribe to PearAI Pro to continue using our features."}
```

I tried logging out and in again on the website, restarting PearAI several times and so on, but I think the 40 requests correspond to those I've used since upgrading from _v0.0.2_ to _v1.0.0_.

Please see images attach for more information

## Expected behavior

Should have logged in successfully and allowed for more requests.

## Screenshots

Invoice:
![image](https://github.com/user-attachments/assets/0c69615a-601c-45c6-935c-5082105db788)

Subscription proof:
![image](https://github.com/user-attachments/assets/9e9150f0-dbc3-42f2-8c22-e43fd4233186)

Problem:
![image](https://github.com/user-attachments/assets/096ace32-a542-48df-a2b8-26bbdb27dd41)

## Additional information

- Version of the extension impacted: _v1.0.0_

**Comment by Fortranibal** [comment]
If you switch from _PearAIServer_ to _PearAIModel_, it seems to be working again

**Comment by nang-dev** [comment]
Talking a look!

**Comment by nang-dev** [comment]
Incredible profile photo btw

**Comment by Fortranibal** [comment]
Thanks! ;)

**Comment by nang-dev** [comment]
As on we talked about on the email, the ~/.pearai config from v0.0.3 before seems to mess the model selection up!

You can continue as is, or you can also delete this ~/.pearai folder, and restart PearAI. PearAI Server should work then :)

Thanks so much for reporting this, and again we really appreciate your support! Feel free to reach back out about ANYTHING! 

If anyone else runs into this after having our beta version, 
Delete the ~/.pearai folder, and restart PearAI :) 

(Note that ~ is home for mac, please use your home directory if you're on windows)
