### ISSUE TITLE
Fix  needing to restart pearai when log-out / new log-in

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#299]
## Context

Currently, to logout you need to restart pearai

## Solution

When logging out, set pearaiaccesstoken  https://github.com/trypear/pearai-submodule/blob/a7e0af65032aba53437ddebe768ed469012b63f3/core/llm/llms/PearAIServer.ts#L25  to null.

this probably means we need a setter in this file

Again: this resetting of this.pearaiaccesstoken should only happen upon logout or new login, not every server_chat request

**Comment by riyuc** [comment]
hi i'll try taking a look at this
