### ISSUE TITLE
[0][Medium][App] File Generation

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#303]
Through our regular chat (`CMD+L`), user should be able to create new files.

- When clicking apply, if file does not exist, it should create the file, then input the code within
- If file already exists, it should directly put the code within (and have that file open)
![Image](https://github.com/user-attachments/assets/04467bff-ef1c-4ff5-be91-26553539ec90)

Difficulties:
- Chat most likely does not know the file directory. How can we have that? Maybe a @Directory tag
- Will likely require prompt optimization.

More context:
https://discord.com/channels/1237009981803462729/1280210117601792000

Currently being worked on by @Himanshu-Singh-Chauhan 

If you'd like to help investigate and experiment, you're welcome to. Many different ways to accomplish this feature.

**Comment by Fryingpannn** [comment]
Currently being done by @Himanshu-Singh-Chauhan

**Comment by nang-dev** [comment]
Incredible job by @Himanshu-Singh-Chauhan
