### ISSUE TITLE
[0][Hard][App] Pear Creator Feature

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#31]
WIP 
Extra modal in PearAI that opens up in side panel (in the future can have full screen mode). Within, have the ability to prompt, which then generates files and code. Users can choose to save changes, reject or apply changes. Why the extra modal? This makes it much easier to make changes to the generated files and code and re-prompt because they appear in a "different context window" than the rest of the files. This is going to be somewhat similar to Cursor's Composer feature, but we're gonna make it open source for everyone to have!

We're trying out a new thing 👀:
OPEN-SOURCE BOUNTY (read more here: https://trypear.ai/blog/open-source-bounties):
Merged: $400
Worthy Attempt: $100

**Comment by nang-dev** [comment]
Aight done pay up 400 bucks
