### ISSUE TITLE
[1][Easy][App] Default PearAI Theme

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#313]
- Solarized Dark for dark mode
- Solarized Light for light theme

Change name to PearAI Dark and PearAI Light.

These should be set as default theme for PearAI

![Image](https://github.com/user-attachments/assets/fe66ccc1-e351-4e91-8176-4b5e4b543e19)

**Comment by Fortranibal** [comment]
Can I try this? Will get onto it tomorrow
