### ISSUE TITLE
[1][Easy][App] `/v0` slash command

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#314]
The `/v0` command should include this in the prompt. It will generate a link to v0 which will include the component the user wants.

The user must be signed in to Vercel.

```
- think carefully about the component
- generate a prompt
- then with the prompt create a clickable link: [component name](https://v0.dev/chat?q={prompt})
- also mention as a reminder that the user must be signed in the vercel.
- make sure prompt is url encoded
```

What this does is it makes PearAI generate a more in depth prompt from whatever the user input, and uses that to prompt v0 to generate a UI component that the user can then copy back to PearAI.

**Comment by djarran** [comment]
This one is ready for review
