### ISSUE TITLE
Toggle between last opened chat and current `CMD+0`

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#33]
## Context
- If the user has a previous chat, pressing `CMD+0` should bring that previous chat to the current chat panel.
- Pressing this key again should bring back the most recent chat.
- If no the user has no previous chat, this command should do nothing.
- A chat that is opened but was never prompted (empty), does not count as a "chat" and should not be switched to.

**Clarification**

Pressing `CMD+0` should always **go back to the most recently opened chat that is not the current opened one**, if there was no previously opened chat, then do nothing.

E.g.:
- User opens Pear
- User opens a new empty chat (Chat#1). Pressing shortcut at this point does nothing because there was no last most recently opened chat.
- User prompts the new chat (Chat#1) with a question about dogs.
- User decides they want to open a new chat (Chat#2) to prompt about a different topic.
- In the 2nd new chat (Chat#2) the user writes some stuff, and decides they want to see the previous chat about dogs again.
- User clicks `CMD+0`, it brings back Chat#1, because it was the most recently opened chat that isn't the current one.
- At this point, if user toggles `CMD+0` again, it will simply switch between Chat#1 and Chat#2.
- If the user stops on Chat#1 and then goes to another different chat (Chat#3) and prompts stuff, then toggling the command would switch between Chat#1 and Chat#3.

**Comment by Trifall** [comment]
> Pressing this key again should bring back the most recent chat.

Need clarification on this - do you mean the chat that was active before pressing the hotkey? 
I.e say there are 5 chats total, and you have chat 3 open, it should go to chat 2; but if you press it again what should happen? Should it go back to chat 3 or go to the latest chat (chat 5)

**Comment by Fryingpannn** [comment]
@Trifall Sorry for delayed response, just saw your comment (feel free ping me in disc if I don't reply). Clarification:

Pressing `CMD+0` should always **go back to the most recently opened chat that is not the current opened one**, if there was not previously opened chat, then do nothing.

E.g.:
- User opens Pear
- User opens a new empty chat (Chat#1). Pressing shortcut at this point does nothing because there was no last most recently opened chat.
- User prompts the new chat with something.
- User decides they want to open a new chat (Chat#2) and prompt something else.
- In the 2nd new chat the user writes some stuff, and decides they want to see the previous chat again.
- User clicks `CMD+0`, it brings back Chat#1, because it was the most recently opened chat that isn't the current one.
- At this point, if user toggles `CMD+0` again, it will simply switch between Chat#1 and Chat#2.

**Comment by andreidimaano** [comment]
fixed in https://github.com/trypear/pearai-submodule/commit/7704abb8b8abc591b3daa3087c7bc49423e2c170

**Comment by Himanshu-Singh-Chauhan** [comment]
https://github.com/trypear/pearai-submodule/commit/561523ac3c434a04ffde1f9d2f9b4c328b2ad6a6
done and merged
