### ISSUE TITLE
[0][Easy][App] Remove Continue from models

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#332]
Remove Continue! We have our own free trial!

This can be reached through Add models -> Other -> scroll down
![Image](https://github.com/user-attachments/assets/8f85e9fd-171f-4336-94d0-231f2a273fc2)

**Comment by nang-dev** [comment]
Get dat shit outta here 🗣️🗣️🗣️🗣️🗣️🗣️🗣️
