### ISSUE TITLE
[0][Medium][App] Preserve "disabled" extensions when copying over extension

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#338]
We copy settings from vscode here upon first time run of PearAI: 
https://github.com/trypear/pearai-submodule/blob/77ed8be46948420b9d83ef00fe25085ed3f97738/extensions/vscode/src/copySettings.ts#L28

It works but the problem is that extensions copied from vscode are "Disabled" but when copied to pearai are "Enabled"

They should be "disabled"

you should figure out where this is being saved and copy it to pearai settings.

how to test/reproduce

delete ~/.pearai , and start PearAI. it will copy files from ~/.vscode over to  ~/.pearai

**Comment by NicholasLe04** [comment]
Found the directory where vscode stores disabled extensions
I can give this a try
