### ISSUE TITLE
Shortcut to start a new chat `SHIFT+CMD+L`

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#34]
- Pressing `SHIFT+CMD+L` should start a new blank chat, replacing current chat.
- Pressing it when chat panel is not opened, or if chat is already blank, should do no action.

**Comment by happinyz** [comment]
Anyone working on this? If not, I'll take a stab at it

**Comment by gedeondoescode** [comment]
> Anyone working on this? If not, I'll take a stab at it

All yours

**Comment by happinyz** [comment]
I see that there's a shortcut `CMD+L` that already starts a new chat. Currently, this shortcut:

1. Opens up a new chat even if the current chat is blank
2. Opens up the chat panel if it is currently closed

Do we really want a new shortcut to implement what's described in the post? imo best thing to do would be to modify the current shortcut such that it **does not** open a new chat if the current chat is blank. It should also still open the chat panel if it is closed. Just some suggestions, open to thoughts!

**Comment by Fryingpannn** [comment]
CLARIFICATIONS!

Expected behavior:
 
- When chat is closed: `CMD+L` opens chat panel (if there was a previous chat, it should open that one)
- When chat is open already: `CMD+L` should do no action (currently it opens a new chat, must fix)
- When chat is open and you have code selected, then `CMD+L` should bring the code within the chat panel.
- When chat is closed: `SHIFT+CMD+L` should open a new chat, regardless of if there was a previous chat
- When chat is open: `SHIFT+CMD+L` should open a new chat and replace the current chat in the panel

Let me know if this clears things up or if you have any other questions!
