### ISSUE TITLE
Support: Use your own OpenAI API key?

### ISSUE THREAD

**Issue by RobErskine** [trypear/pearai-app#357]
Hi there,

Thanks for building Pear! I'm loving it so far. I had a question around using my own API key / models. On the pricing page the Free tier says:

> Use our free trial, **your own API key**, or local models.

I can't find anywhere to seemingly set up my own OpenAI key or anything. I see the models outlined in `~/.pearai/config`, but not sure how to set up a custom provider. I saw in the documentation for Tab Autocomplete you can drop in your own Codestral key. Is that what Intern tier is referring to? Or is there some other place where this can be set up?

![Arc-Pricing - PearAI_2024-09-25 at 16 39@2x](https://github.com/user-attachments/assets/3f6d190c-78d9-412b-b5a0-c0911b226415)

Thanks for your time! - Rob

**Comment by cqdev-co** [comment]
![image](https://github.com/user-attachments/assets/56e07886-d49f-4863-bf23-b21e3b89b906)

Add Model -> Other Model -> Go from there

**Comment by cqdev-co** [comment]
@RobErskine

**Comment by RobErskine** [comment]
@cqdev-co Ack ok, can't believe i missed that. Thank you.

**Comment by akashp1712** [comment]
Sorry for bothering the thread,  @cqdev-co , I'm not able to find the space in the Image you've showed.
Is it from VSCode settings ?

**Comment by akashp1712** [comment]
Oh shoot!, I found it in the PearAI chat window.
