### ISSUE TITLE
Display 3 major shortcuts in their appropriate locations.

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#37]
## Context
- All shortcuts should be clear and visible. 
- No guessing should be needed from the user. 
- Babysit users to know which shortcuts to use.

Partial PRs are accepted for this task. Each shortcut needs to be displayed somewhere on the UI such that the user knows it's the shortcut needed for a specific task. For this issue, the 3 shortcuts to be displayed are:

1. Opening chat `CMD+L`
2. Closing chat `CMD+:`
3. Dynamic resizing of the chat `CMD+[`

For Windows, we should be able to detect the user's OS, and indicate `ALT+L`, `ALT+:`, and `ALT+[` instead.

## Example

- Indicate opening chat here (if chat closed, say "open chat `CMD+L`", if chat already open, text would be "close chat `CMD+:`"
<img width="336" alt="image" src="https://github.com/trypear/pearai-app/assets/59063950/6d55ea32-a86d-4b04-a65e-96a0b07bc922">

- The enlarge chat panel shortcut (https://github.com/trypear/pearai-app/issues/20) should be shown to the user explicitly
   - Remove the parentheses in the picture. Shortcuts should have a darker background behind them and just be the words directly e.g. `CMD+[`
<img width="239" alt="image" src="https://github.com/trypear/pearai-app/assets/59063950/3e47e3d5-dfb4-487e-b5a6-f40ea639ae62">

**Comment by shrix1** [comment]
I will work on it

**Comment by Himanshu-Singh-Chauhan** [comment]
I will work on this.

**Comment by shrix1** [comment]
- Check `actionbar.ts`, where the VSCode side layout switching option is located on the right side (for adding OpenChat shortcut UI).
- Enlarge the PearAI chat UI. This code is inside the pearai-submodules folder.

**Comment by Fryingpannn** [comment]
SOLVED https://github.com/trypear/pearai-submodule/pull/101
