### ISSUE TITLE
Make a PearAI logo!

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#38]
This is what our current logo looks like. Very very basic stock image logo of a pear. We need a better one!

<img width="225" alt="Screenshot 2024-05-21 at 10 38 44 PM" src="https://github.com/trypear/pearai-app/assets/59063950/ca082456-7db3-405f-87e7-ebf30e416d38">

Tracked here: https://discord.com/channels/1237009981803462729/1243020418109935678/1244868314522583094

Sizes needed in PNG:

- 70x70
- 150x150
- 192x192
- 16x16
- 32x32
- 128x128
- 256x256
- 512x512

And one in `.svg`

**Comment by Alexx1105** [comment]
I can do this in figma, is the logo you need meant to be for an app icon?

**Comment by Fryingpannn** [comment]
@Alexx1105 saw you alr joined the discussion in discord, but yes
