### ISSUE TITLE
Discord bot to create issues

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#43]
Discord bot that can create issues in this repository to reduce friction for issue creations.

- Message to create an issue: `/issue [title] [msg]` 
- Should return the link of the issue for further edits.

**Comment by EllisCreations** [comment]
I'm working on it!

**Comment by Zhreyu** [comment]
> I'm working on it!

me too along with Ellis!

**Comment by conorquinlan65** [comment]
@EllisCreations @Zhreyu Excited to see what you guys build! :)
