### ISSUE TITLE
Ability to @files in the chatbox 

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#44]
## Context

We should be able to tag files. and then the contents of the file should be passed to the LLM as part of the question

<img width="593" alt="Screenshot 2024-05-22 at 8 43 47 PM" src="https://github.com/trypear/pearai-app/assets/5115108/92969e02-1ec0-44a1-a8ec-9573cf5226da">

**Comment by happinyz** [comment]
What should happen if the file is massive, and exceeds the LLM's max token count?

**Comment by nang-dev** [comment]
@happinyz 

Yeah, for the first PR on this, we can just tell the user that the file is too big

We will eventually chunk the file (that can be done at the same time, https://github.com/trypear/pearai-app/issues/46)
