### ISSUE TITLE
Improving Cloning and Contribution Accessibility

### ISSUE THREAD

**Issue by ItWasEnder** [trypear/pearai-app#49]
### Improving Cloning and Contribution Accessibility

Originally, there were issues with submodules in the main repository not being initialized when contributors tried to build. We need a solution to streamline this process and make it easier and more intuitive to start contributing.

For further discussion, refer to the [Discord thread](https://discord.com/channels/1237009981803462729/1243697081030541354/1243697081030541354).

**Comment by nang-dev** [comment]
completed :D
