### ISSUE TITLE
Adding multilanguage Readme or contribute guildline to attract more contributors or users.

### ISSUE THREAD

**Issue by bomin0624** [trypear/pearai-app#51]
## Is this request related to a problem? Please describe.

Hi, Just watch the video on Youtube. 

Love the idea and the product, maybe the multiple language introduction of this app can attract more developers and users to join the product. 

I can contribute the Chinese (traditional and simplified) and Japanese part.

## Describe the solution you'd like

- Adding the Chinese or Japanese Readme, maybe you guys can use ChatGPT to generate one.

**Comment by nang-dev** [comment]
Yeah I like this idea a lot! I wonder how the multilanguage readme would work in github - do you have a link of a github repo that already does this?

**Comment by bomin0624** [comment]
This is an example of [Japanese Natural Language Processing tools and libraries list](https://github.com/taishi-i/awesome-japanese-nlp-resources).
Maybe you guys can have a check!
