### ISSUE TITLE
Automatically copies VSCode settings without asking

### ISSUE THREAD

**Issue by s1050613** [trypear/pearai-app#58]
## Describe the bug
When opening for the first time, PearAI copies your VSCode settings and extensions without asking the user.
This uses potentially gigabytes of storage even if the user didn't want to use these extensions.

## How to reproduce
1. Install and open PearAI

## Expected behavior
A popup appears asking users if they would like to import their VSCode settings/extensions.

## Screenshots
![image](https://github.com/user-attachments/assets/7895276b-73f1-45a8-9d08-da50d4299b67)

## Additional information

- Version of the extension impacted: _Latest_

**Comment by fardin-developer** [comment]
Hey I want to work on this issue, please assign me.

**Comment by charlwillia6** [comment]
I think this has been fixed and implemented.  @nang-dev @Fryingpannn

**Comment by timknappe** [comment]
If so could smn point to a commit, I could use the implementation for another issue.

**Comment by Himanshu-Singh-Chauhan** [comment]
@s1050613 please download the latest version, we fixed this.

**Comment by Himanshu-Singh-Chauhan** [comment]
this is fixed. user is now prompted to import on onboarding screen.
