### ISSUE TITLE
Improve 'Get Started Deving' Onboarding

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#59]
trying to get started deving makes me want to kill myself. I'll try again when back in nyc haha. In the "Build and Run" section of the contributing, should all of those things be vscode? or does it need to be updated? https://github.com/trypear/pearai-app/blob/main/CONTRIBUTING.md#packaging

- connor

**Comment by Fryingpannn** [comment]
Most of this got done thanks to @Trifall ! still might be some details remaining so will keep this issue open
