### ISSUE TITLE
Improve buttons for interacting with code from prompt responses

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#61]
## Context

Currently, when code is generated in Pear chat, you need to hover over the code text block for the action buttons to appear. This is bad UX. they should show up by default.

- Remove the "Apply" button on UI (the first one), only the "Apply at cursor" and "Copy" buttons are necessary (you can hover over button to see the text). 
   - This is because one can simply do `CMD+A` and then click "apply at cursor" and it'll do the same thing. Should declutter the UI with less buttons.
- Should not have to hover over button to see the button's functionality. Include description right beside the buttons, e.g. "Apply at cursor", "Copy". You may have to play around a bit here to see where the text fits best. Can be small text right below or beside the buttons.

The first button is "Apply", second is "Apply at cursor" and third is "Copy"
<img width="455" alt="image" src="https://github.com/trypear/pearai-app/assets/59063950/d309268f-4918-476a-b808-92766a85d2b9">

## To reproduce
You will need an API key for this. Sign up at [OpenAI ](https://platform.openai.com/api-keys)to get one.
- Simply prompt the code to print 1 to 10, for which it'll generate the code for.
- Hover over the generated code text block. The buttons on top would appear.
<img width="1532" alt="image" src="https://github.com/trypear/pearai-app/assets/59063950/415ff6bb-c78c-41f8-b36e-1d422db7a9e6">

### Next step
- Next step would be to have shortcut keys for the copy and apply at cursor buttons from the generated code, and have these shortcuts displayed on the UI. But this can be for another PR.

**Comment by jspEclipse** [comment]
My Issue

**Comment by jspEclipse** [comment]
![image](https://github.com/trypear/pearai-app/assets/96797930/d29692a7-8d41-4c9c-9923-fa24a251786a)
![image](https://github.com/trypear/pearai-app/assets/96797930/e6fc7e7f-5a8e-493f-8482-5fa6ac9ea6a8)
Reminder to myself to also look into making sure that all buttons darken onHover

**Comment by jspEclipse** [comment]
I sent my PR through pearai-submodules repo
