### ISSUE TITLE
Find a way to "hot reload" / make it so you don't have to restart the app with ./scripts/code.sh to see your changes

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#65]
## Context

Find a way to "hot reload" / make it so you don't have to restart the app with ./scripts/code.sh to see your changes

This is NEEDED

**Comment by Dmedina20** [comment]
TLDR: https://blog.hediet.de/post/hot_reload_for_vs_code_extension_development

**Comment by Himanshu-Singh-Chauhan** [comment]
1. setup project by reading [Contributing docs](https://github.com/trypear/pearai-app/blob/main/CONTRIBUTING.md)
2. run `yarn watch` in a terminal - wait for it to compile everything (around 2 mins), it then shows "finished compiling", keep it running.
3. open another terminal to run the app `./scripts/code.sh`
4. now every time you make a change, yarn watch will pick up those changes and will only compile that, almost instantly. (save your changes manually)
5. reload the windows to see the changes. (Command Palette -> reload window)

- changes to both code editor itself and extension (submodule) are compiled or hot reloads.
- you can use `yarn watch-client` if you are only making change to the code editor.

**Disable 'Auto Save' feature, save your changes manually. (auto save triggers yarn watch on every change, causing it to hang or crash).**

**Comment by nang-dev** [comment]
Thank u himanshu! Added to the docs
