### ISSUE TITLE
[1][Easy][Submodule] Make a loading animation when `CMD+I` is in motion

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#82]
Right now there is no indication that `CMD+I` is running after you press enter. There should be an indication somewhere, anywhere, that indicates it is loading.

Maybe a loading animation here (spinner?), after user presses enter. Before closing it once response comes.

![Image](https://github.com/user-attachments/assets/6f110556-374e-4bd5-8eff-7421a7586eb2)

**Comment by Himanshu-Singh-Chauhan** [comment]
https://github.com/trypear/pearai-submodule/pull/88
