### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#96]
Can anyone make the equivalent of 

build-extensions.sh (in extensions/pearai-submodule)
code.sh  (that uses this ^) 

for windows (Once the v0 merge happens?)

Changes to contributing.md for windows would be great too with this!
Thank you so much

**Comment by gedeondoescode** [comment]
I'll do it, should be simple enough

**Comment by gedeondoescode** [comment]
Should now work on Windows! Thanks @Fryingpannn @ItWasEnder
